### PR TITLE
Update translations from crowdin

### PR DESCRIPTION
**Pull request by vincent99**
@loganhz, can you look at zh-hant and why there's so many lines removed?  Not clear to me if they are things that were never traditional, were intentionally removed, were the same as simplified, were mistakenly removed, or what.

### CODE REVIEW

**Comment by loganhz** [comment]
@vincent99 
@xiaoluhong updated the both zh-hans and zh-hant in code directly. I guess we should keep the current zh-hant in our repo.

**Comment by xiaoluhong** [comment]
@vincent99 Hi, I translated it directly through the repo, not in the crowded translation，Basically keep the Chinese and English synchronized.

**Comment by vincent99** [comment]
Oh ok, I'll pull it out then.  You should be periodically pushing those to crowdin, or we need to remove it as a language there and only take PRs.

**Comment by xiaoluhong** [comment]
We choose zh-hans and zh-hant to submit it through PR, which will be more convenient. Thank you.

**Pull request merged**
