### PR TITLE
Update created column style

### PR DESCRIPTION
**Pull request by loganhz**

### CODE REVIEW

**Comment by westlywright** [comment]
@vincent99 Can I get your feedback on this? I am not opposed to adding these but some of the headers already look pretty scrunched on smaller screens. 

@loganhz what was the reason behind this change?

**Comment by loganhz** [comment]
Some user wants to see the created time for volume, dns record and load balancer. But I add it everywhere in this PR.

**Comment by loganhz** [comment]
Removed `created` columns in cluster list page and node list page.

**Comment by vincent99** [comment]
This seems like something that should go on detail pages, but not be in tables in general.  The ones where we do have it are just because there's nothing else of interest to show in a table, but on the common types it's going to take up a lot of room for something that is not very useful in most cases.

**Comment by loganhz** [comment]
@westlywright Removed all newly added created columns.  Refined the style for created column in this PR.

**Pull request merged**
