### PR TITLE
Support to edit project name

### PR DESCRIPTION
**Pull request by loganhz**
## Proposed changes

Support to edit project name. the `update` of `name` field  is true in the project schema. Some user wants to edit it via UI. Now we can only do it via API.

## Types of changes

What types of changes does your code introduce to Rancher?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Issues

Link any related issues, pull-requests, or commit hashes that are relavent to this pull-request.

If you are opening a PR without a corresponding issue create an issue before you do. This will help QA massively. PR's opened without linked issues will not be merged until an issue is created and linked here. 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
_Tip: `yarn lint` or `npm run lint`_
- [ ] Any dependent issues or pr's have been linked
- [ ] If updating dependencies, `yarn.lock` file has been updated and committed

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by vincent99** [comment]
I feel like this was disabled for a reason... @cjellick ?

**Comment by cjellick** [comment]
No reason that I am aware of and the field is editable in the API. @alena1108 you know of any reason we need to disallow project name editing?

**Comment by alena1108** [comment]
@cjellick is it a display name? or a real project name. I believe the name is used in a project id annotation on namespaces to link them back to the project.

**Comment by loganhz** [comment]
I guess it is a display name as space is allowed in the field and we can create two projects with the same name.

image

**Comment by vincent99** [comment]
okay, fair enough 👍

**Pull request merged**
