### PR TITLE
Support logging SSL for splunk, ES and kafka

### PR DESCRIPTION
**Pull request by n313893254**
Related issue:
https://github.com/rancher/rancher/issues/13526
https://github.com/rancher/rancher/issues/13065

### CODE REVIEW

**Comment by aiwantaozi** [comment]
https://github.com/rancher/rancher/issues/13755

**Comment by vincent99** [comment]
You have basically the same thing over and over.  Make a component instead of copying and pasting and compiling the same ssl config repeatedly.  Every byte of template you put in is several bytes every user has to download.

And there's already an advanced-section component.

**Comment by n313893254** [comment]
Thank you for review, I will modify the code.

**Comment by n313893254** [comment]
@vincent99 Fixed

**Pull request merged**
