### PR TITLE
Added t2.nano and t2.large EC2 instance types

### PR DESCRIPTION
**Pull request by DanielBodnar**

### CODE REVIEW

**Comment by vincent99** [comment]
@DanielBodnar can you squash this into one commit please?

**Comment by DanielBodnar** [comment]
@vincent99 Sure thing. First time doing that - this look right?

**Comment by vincent99** [comment]
Still looks like 2 commits ("DanielBodnar wants to merge 2 commits...");  Maybe you forgot to push?  You want something like:

```
git rebase -i HEAD~2
# change the 2nd "pick" to "fixup" and save/quit
git push -f
```

**Comment by DanielBodnar** [comment]
@vincent99 There we go, thanks for showing me how to do that.

**Comment by vincent99** [comment]
Looks good, thanks

**Pull request merged**
