### PR TITLE
fix 3600

### PR DESCRIPTION
**Pull request by lvuch**

### CODE REVIEW

**Comment by vincent99** [comment]
@lvuch: `overflow: hidden` is no bueno.. When you have a short page it makes long drop downs in the header cut off.  The right fix for this is `clearfix` on the containing element of the template boxes.

**Comment by ibuildthecloud** [comment]
We don't need to fix 3600, the 2600 was just fine

**Comment by vincent99** [comment]
But the 5200 was cooler...

**Comment by lvuch** [comment]
@vincent99 you're are right, I switched it

**Pull request merged**
