### PR TITLE
catalog certification

### PR DESCRIPTION
**Pull request by lvuch**

### CODE REVIEW

**Comment by loganhz** [comment]
related issue https://github.com/rancher/rancher/issues/14574

**Comment by guangbochen** [comment]
Can we please also add `experimental` label to the catalog certification, need it for catalog apps like longhorn and nfs-provisioner, thanks.
```
io.rancher.certified: Experimental
```

**Comment by vincent99** [comment]
`rancher` and `partner` show text from a translation and special colors; any other arbitrary value shows the text in a third color.  So you can put in experimental if you want.

**Comment by vincent99** [comment]
image

**Comment by guangbochen** [comment]
thanks, it works but only the UI seems slightly different the above post.
And it only works for Rancher Library catalog correct?
image

**Comment by vincent99** [comment]
That's the old screen, I haven't updated the latest2 build yet.

**Pull request merged**
