### PR TITLE
Support more alert group config

### PR DESCRIPTION
**Pull request by n313893254**
Proposed changes
======

Types of changes
======

- New feature (non-breaking change which adds functionality)

Linked Issues
======

https://github.com/rancher/rancher/issues/15663

 

Further comments
======

### CODE REVIEW

**Comment by n313893254** [comment]
@westlywright Done, thanks for your review.

**Comment by davidnuzik** [comment]
@n313893254 could you very briefly describe at a high level the changes? What new config has been added? Proposed changes section is blank

**Comment by loganhz** [comment]
We will post the change soon

**Comment by n313893254** [comment]
sure

**Pull request merged**
