### PR TITLE
update pt-br translation

### PR DESCRIPTION
**Pull request by paulobezerr**
Proposed changes
======

I have tried to use `scripts/update-translations` script but did not work.
Maybe this is why I did not see translation result in new UI version.

Then, I decided to send a pull request with updated PT-BR translations.

Types of changes
======

- Translations

### CODE REVIEW

**Comment by vincent99** [comment]
Only English and Chinese are maintained by us in-repo.  The rest are maintained in https://crowdin.com/project/rancher-ui and periodically pulled into here (which is what `update-translations` does).

**Comment by paulobezerr** [comment]
Well, there is a long time without updates in pt-br translations.
Can we automate this?

**Comment by vincent99** [comment]
They are updated usually before major releases.  What's sitting there and not approved is a tiny fraction of the missing translations for pt-br, so it's not exactly going to make a huge dent even if it were merged.

**Comment by paulobezerr** [comment]
@vincent99, honestly speaking, keep working on translations and see no changes but in major releases demotivates.

This pull request is huge and only have Crowdin translations.
I know that is "only" 26% of translations, but it is already lot.

IMHO this should be updated in every version for all languages.

**Comment by vincent99** [comment]
There are **16** strings in CrowdIn pending approval that are not already in master.  I don't know how long they've been pending off-hand, but out of ~5000 that's basically noise.

This PR obviously contains more, but CrowdIn is the mechanism by which we manage translations for all languages other than en-us and zh-hans, not PRs.  It also contains thousands of lines of duplicate English keys.  English is already the fallback if there is not a translation found in the selected language, it doesn't need to go in the translation files N times.  The translation file should include only the keys that are actually translated.

**Comment by paulobezerr** [comment]
Got it, sir.

But maybe we should check what is happening, because translations accepted 2 mounts ago are not in master.

### Example

The term `Saving...` was translated to PT-BR as `Sanvando...`.
But two months ago I have accepted the correct one: `Salvando...`.

image

This term isn't in master yet.

Could you help on it?
Can we accept translations in a shorter time?

**Pull request closed without merging**
