### PR TITLE
UI tweaks to host page layout

### PR DESCRIPTION
**Pull request by westlywright**
* reworking the group/stack view
* removed the container view
* remove old styling

### CODE REVIEW

**Comment by vincent99** [comment]
- reduce padding on all the things
- replace |v| menu with vertical ellipsis on right

**Comment by westlywright** [comment]
:+1:

**Comment by vincent99** [comment]
- [ ] Right-align IP Addresses (if possible while still having name clip properly?):

image

- [ ] Min-column width looks bad:

image

- [ ] Trailing vertical line dividers:

image

- [ ] Can we replace all the action menus with ellipsis so it's consisent?

image

- [ ] I don't think we need the empty sidekick row/`groupHasChildren` logic any more with one thing per row.. only show sidekicks if there are some:

image

- [ ] Add container has more space on top than bottom:

image

- [ ] Unequal spacing (but a large actual target area for the menu is good):

image

- [ ] action-menu-tooltip being fixed-width spreads to regular action menus after one is shown:

image

**Comment by westlywright** [comment]
@vincent99 updates made :+1:

**Pull request merged**
