### PR TITLE
Show links in stack description

### PR DESCRIPTION
**Pull request by loganhz**
[related issue 5282](https://github.com/rancher/rancher/issues/5282)

image

### CODE REVIEW

**Comment by loganhz** [comment]
@vincent99 please let me know if I need to apply this to other descriptions.

**Comment by vincent99** [comment]
The linking logic look good but it needs to escape everything that **isn't** a link and return a `.htmlSafe()` string so that you don't need triple-`{`.

As-is this allows arbitrary HTML injection onto the page via anything shown in a banner (try setting your description to `<b>hi</b> http://google.com`), which is very bad.

Also there are lots of other descriptions (service, container, etc detail pages) that should be linkable too.

**Comment by vincent99** [comment]
You can also actually load kevva/url-regex via npm instead of copying it.  Add to pacakge.json and `import urlRegex from 'npm:url-regex';`

**Comment by loganhz** [comment]
@vincent99 updated.
thanks for your comments.
It looks like I can change `banner-message` component as all descriptions are using it.

**Comment by vincent99** [comment]
All descriptions may be banners, but not all banners are descriptions... I haven't tried this but expect it breaks any that are given HTML input, like anything that already has an `<a href="http://blah">` in it will get double linked.  

Please leave banner as-is and linkify the input to it when used for descriptions.  Or add a `displayDescription` which does linkify to mixins/cattle-transitioning-resource and use that for the banner input.

**Comment by loganhz** [comment]
@vincent99 done.

**Pull request merged**
