### PR TITLE
feat: harvester nodeDriver rke1

### PR DESCRIPTION
**Pull request by WuJun2016**
Proposed changes
======

Add harvester node driver for RKE

Types of changes
======

New feature
Filter inactive nodedriver

Linked Issues
======
 
[3374](https://github.com/rancher/dashboard/issues/3374)
Further comments
======

Add the credential related to the harvester

### CODE REVIEW

**Comment by guangbochen** [comment]
@vincent99 can u PTAL, thanks

**Comment by vincent99** [comment]
@yasker @guangbochen Probably something to discuss in in a meeting, but I'm not sure why we'd want this to be available for RKE1 / Ember in the first place?

**Comment by yasker** [comment]
@guangbochen @WuJun2016 What's our plan regarding the cloud credential backend API?

**Comment by guangbochen** [comment]
for now, we are just using the same mechanism of the RKE1 cloud credentials which is the secret.
image

**Comment by vincent99** [comment]
It's going to be weird in 2.6.0 for Harvester to be an option to add a Cloud Credential when the driver isn't enabled, and doesn't even exist.  Can you add filter to the list so that only drivers that are enabled are offered as choices? (This should hide others that are currently shown when not enabled, like phoneixNap)

**Comment by WuJun2016** [comment]
@vincent99  has been filtered inactive nodeDriver.  can u PTAL, thanks

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/33821

**Comment by deniseschannon** [comment]
@WuJun2016 Could you help make a PR that has the filtering for the inactive node driver for the 2.5-fixes branch? Since that fix is generic for all of Rancher, I was hoping to cherry pick that change into 2.5-fixes, but you have 1 commit for all your Harvester changes. 

Thank you!!

**Comment by WuJun2016** [comment]
@deniseschannon   Done.    
https://github.com/rancher/ui/pull/4722

**Comment by deniseschannon** [comment]
@WuJun2016 There is an issue where we are filtering out cloud credentials that have active cluster drivers (example is google), but no active node driver. Can you update/create a new PR for that fix? This was mentioned in slack, but not sure if it made it into any GH issue.

**Comment by WuJun2016** [comment]
@deniseschannon   fixed this bug on 2.5-fixes branch and master branch.

**Comment by WuJun2016** [comment]
@deniseschannon   done,  fixed on 2.5-fixes branch and master branch

**Pull request merged**
