### PR TITLE
Support for app catalog question variable type "config-map"

### PR DESCRIPTION
**Pull request by bashofmann**
Proposed changes
======
This adds a new question variable type `config-map` that renders a UI element to pick existing ConfigMaps when installing/upgrading a catalog app, similar to the already existing variable type `secret`.

Types of changes
======
- New feature (non-breaking change which adds functionality)

Linked Issues
======
https://github.com/rancher/rancher/issues/27412

Further comments
======
The UI component to pick ConfigMaps already exists, so it is only necessary to add this as a supported variable input type.

Tested with this helm chart https://github.com/bashofmann/chart-repo/tree/master/charts/rancher-demo/v0.1.0.

### CODE REVIEW

**Comment by bashofmann** [comment]
If this gets merged, I'll also create an PR for the docs then.

**Comment by westlywright** [comment]
@bashofmann This can't be merged in its current state. Adding the type to the supported schema types works and the `input-configmap` component input shows up on the app, but there are other issues with this.

All project level apps default to launching in there own namespace, so any app that features this will have empty config maps dropdown unless the configmaps been created in the potential namespace before hand. This is pretty hard to do unless you understand when creating a new app the UI defaults to creating a new namespace from the app name unless a matching namespace already exists, then we append a random string to the app name. Or they select a namespace with config maps in them. 

Additionally I am not sure how we handle this case at the global app level? Global Apps are on a per project basis where namespace creation is augmented by the backend where the namespace is created for the app (rather then the front end) when the app is created and deployed in each target project. We'd have to load all the namespaces for each project they've selected and then all the config maps.

@vincent99 may have additional info as to why we've never fully implemented this as a supported app question as well. 

There may be a way we can implement a configmap question type that I haven't thought about but we'll need to consider these requirements when doing so and will require a larger effort to implement.

**Comment by bashofmann** [comment]
Thanks for the detailed information. When testing it I completely forgot that you can add project level secrets that are created in every namespace and because of that it looked like the limitation of configmaps is the same as with secrets.

Do you know if there is a specific reason why project level configmaps haven't been implemented yet?

**Comment by westlywright** [comment]
@bashofmann I can't recall any specific reason they have not been implemented.

**Comment by westlywright** [comment]
@bashofmann I am going to close this for now, if this is something you think we should move forward though please bump the issue up to the PMs so we can start discussing if this is possible.

**Pull request closed without merging**
