### PR TITLE
iframe issues in vue from ember

### PR DESCRIPTION
**Pull request by lvuch**
- [x] https://github.com/rancher/dashboard/issues/3370
- [x] https://github.com/rancher/dashboard/issues/3371
- [x] https://github.com/rancher/dashboard/issues/3404
- [x] https://github.com/rancher/rancher/issues/33449
- [x] https://github.com/rancher/rancher/issues/33450
- [x] https://github.com/rancher/rancher/issues/33469

### CODE REVIEW

**Comment by lvuch** [comment]
there are a few remaining js issues
- fixed header table scroll (predates my ember/vue port fixes)
- " I cannot access the Load Balancing tab in the local cluster. Errors with Uncaught (in promise) Error: There is no route named ingress. I can access the Load Balancing tab in a downstream cluster."
- "Clicking Refresh Kubernetes Metadata does not show a confirmation that metadata has been refreshed. A notification on the top right used to appear."

**Comment by nwmac** [comment]
@lvuch Its very hard to review this PR - you seem to have different editor settings, so your editor has formatted the files differently, resulting in lots of changes - its hard to see what you've actually changed.

Also, this is up to 76 files - we should aim for smaller PRs that are focused on fixing a specific issue - these are easier to review.

**Review by nwmac — CHANGES_REQUESTED** [review]
Can you redo this PR and turn off your formatting, so you are not reformatting on save - there are some changes like this:

WAS: <td data-title="{{t "formPorts.containerPort.label"}}">
NOW: <td data-title="{{t " formPorts.containerPort.label"}}">

where your editor has added a space at the start of the string - I don't think this is right and we need to keep the existing formatting.

**Comment by nwmac** [comment]
@lvuch I'm also concerned - the original aim was to make some minor changes to better align the styling - we seem to have gone beyond that

**Review by nwmac — APPROVED** [review]

**Pull request merged**
