### PR TITLE
tweak add cluster provider selection

### PR DESCRIPTION
**Pull request by westlywright**

### CODE REVIEW

**Comment by vincent99** [comment]
`:%s/emport/import/g`

**Comment by westlywright** [comment]
emport == neu

**Comment by vincent99** [comment]
But it's never just the bare word 'import'

**Comment by vincent99** [comment]
image

Things need to line up better, this is currently just assuming there's exactly the right number of node drivers to make Custom end up under "Bring your own";  2x2 grid of

```
|--span-10----------|--span-2-|
| Kontainer engines | Import  |
|  .. maybe more .. |         |
|  .. 5 per row ..  |         |

|-------------------|---------|
| RKE node drivers  | Custom  |
|  .. maybe more .. |         |
|  .. 5 per row ..  |         |
|-----------------------------|
```

Also random capitalization in the labels, and "hoseted" -> "hosted"

**Comment by westlywright** [comment]
updated and fixed issues

**Pull request merged**
