### PR TITLE
Project level resource quota

### PR DESCRIPTION
**Pull request by loganhz**
https://github.com/rancher/rancher/issues/13277
https://github.com/rancher/rancher/issues/14620

### CODE REVIEW

**Comment by vincent99** [comment]
This looks good but is missing one piece;  On a namespace create/edit you need to be able to choose which quota template is used (`resourceQuotaTemplateId`).    That should probably also be a column in the namespace table.

**Comment by loganhz** [comment]
@vincent99 Done. Now user can only select `resourceQuotaTemplateId` when create/edit a namespace under a project which has `resourceQuota`  field.  
Alena said we would allow user to select `resourceQuotaTemplateId` for all namespaces later.

**Comment by vincent99** [comment]
One more thing, can you make memory fields take `MiB`, cpu `milli CPUs` like the workload definition do (and storage fields in 10^9 `GB`):

image

So that the user can just type in a number instead of having to put in a unit.

**Comment by loganhz** [comment]
@vincent99 Done

**Pull request merged**
