### PR TITLE
Refactor settings page

### PR DESCRIPTION
**Pull request by westlywright**
* break individual sections into there own components and let them handle the saving of there own data
* Add new dynamic driver settings component

### CODE REVIEW

**Comment by vincent99** [comment]
- Virtual Machines doesn't seem like it needs a cancel button
- I'd just call the section "Machine Drivers".  You'll be able to both add and remove from the list of available ones soon.
- The add machine driver button is in an odd place, (+) buttons are usually to the left just above the table.
- "URI" in all caps, or URL
- "MD5 Checksum"
- Is description shown anywhere?  If not no point asking for it
- Some help text under each field of the add screen would be helpful to know what to enter.. e.g. The URL to download the machine driver for Linux/amd64, the expected MD5 hash of that download
- View in API links on machine drivers are broken/404, should go to /v1/machineDrivers/1m1 not /v1/projects/1a5/machineDrivers/1m1.

**Comment by vincent99** [comment]
User `{{settings.appName}}`, never "Rancher" anywhere that might be private-labeled.

**Comment by westlywright** [comment]
Comments addressed, should be GTG.

**Comment by vincent99** [comment]
LGTM, need backend support merged

**Pull request merged**
