### PR TITLE
Adding the agent env vars to rke drivers.

### PR DESCRIPTION
**Pull request by codyrancher**
Proposed changes
======
Adding the agent env vars to rke drivers.

Types of changes
======
- New feature (non-breaking change which adds functionality)

Linked Issues
======
rancher/rancher#31023

image
image

### CODE REVIEW

**Comment by codyrancher** [comment]
@westlywright just a note about rke templates. I disabled this for rke templates because the templates really don't seem to have great support for arrays/objects. I attempted to kludge it in but ended up with a worse mess. If it's something we want to be able to template I think we should put it into a separate issue as it adds a lot of scope.

**Review by westlywright — CHANGES_REQUESTED** [review]
Didn't find anything specific in the code but when running it, when I edit a fresh linode cluster and select the secret type I get an undefined error.

**Comment by westlywright** [comment]
@codyrancher looks like a minor bug with the `Secret` type. Also I think that not doing the templates is okay for now. Can you comment on the ticket so it is clear to whomever may wonder?

**Comment by codyrancher** [comment]
Disabling secrets and configmaps if they aren't available. This also simplified the interface of FormAgentEnvVar by getting rid of the showSecrets/ConfigMap props.

image

**Review by westlywright — APPROVED** [review]

**Pull request merged**
