### PR TITLE
Support bulk actions for pod list in workload detail page

### PR DESCRIPTION
**Pull request by loganhz**
https://github.com/rancher/rancher/issues/15074

### CODE REVIEW

**Comment by vincent99** [comment]
This might be nice but it's not solving the problem of why there's 70 pods to need to be deleted in the first place..

**Comment by loganhz** [comment]
removed the `resolved` label in the issue

**Comment by westlywright** [comment]
@loganhz where are we at with this? I don't see a problem with the bulk actions but like @vincent99 said it doesn't solve the problem of the 70 extra pods being created. Is there a bug on the backend or a selection of options we should default to on this page?

**Comment by loganhz** [comment]
Created an new issue for supporting bulk actions in workload detail page. rancher/rancher#15074

I guess we can use https://github.com/rancher/rancher/issues/14985 to track the backend issue.

**Comment by loganhz** [comment]
Hi @westlywright , I think we can merge this PR as there is no backend dependency for issue rancher/rancher#15074.

For the backend issue, we can track it with rancher/rancher#14985.

**Pull request merged**
