### PR TITLE
Provide option to set Administrative flag for cluster scoped roles

### PR DESCRIPTION
**Pull request by loganhz**
Proposed changes
======
Provide option to set Administrative flag for cluster scoped roles

Types of changes
======
- New feature (non-breaking change which adds functionality)

Linked Issues
======
https://github.com/rancher/rancher/issues/17443
 

Further comments
======

### CODE REVIEW

**Comment by vincent99** [comment]
I have no idea what the administrative flag is for from this.

**Comment by loganhz** [comment]
@alena1108 @mrajashree what's the difference between `true` and `false` 
 for `Administrative` field?

**Comment by loganhz** [comment]
From @mrajashree 

```
The name of the flag should be Administrative.
The reason behind adding this is, managing access to resources that are both, cluster scoped and project scoped, for example the `catalogtemplates` and `catalogtemplateversions`. If any cluster role has Administrative set to `true`, then that cluster role will get access to all catalogtemplates/versions from all projects that are a part of that cluster. Which is why cluster-owner has by default Administrative bit set to true; but cluster-member doesn't since cluster-members should not have access to catalogtemplates/versions from projects that they don't belong to, even if that project is in the cluster they are a part of. So in short this flag if set will grant cluster-scoped roles access to all resources across all projects in the clusters they are added to, and should be set only if the role being added is expected to be equivalent to a cluster-owner role
```


@vincent99 Any suggestion for the label and help text for that?

**Comment by cjellick** [comment]
I explained this field to @vincent99 and we talked through the usecases and we decided that we dont want to expose this field in the UI. it should be set for our existing cluster admin roles, but we will just hide it. If people complain about custom roles, they can in the short term flip the bit in the API and then we can figure out the right way to explain what it does.

The problem is that it is fairly confusing and requires understanding how rancher does authz to fully grok

**Pull request closed without merging**
