### PR TITLE
minor tweaks for rancherio > rancher

### PR DESCRIPTION
**Pull request by Rucknar**
Spotted these, thought i'd offer a branch with them updated, let you guys focus on more important things!

### CODE REVIEW

**Comment by vincent99** [comment]
@Rucknar thanks; not sure why but this says it has conflicts

**Comment by Rucknar** [comment]
Yea, surprised me that one. It's literally the smallest of changes and branched minutes before the pull request!. Seems to suggest i can't fix the merge either :(

**Comment by vincent99** [comment]
@Rucknar it's because your fork was made a while ago and not pulled up to date, it's ~300 commits behind.. 

```
git remote add upstream https://github.com/rancher/ui.git # if not already setup
git fetch upstream
git rebase upstream master
# fix conflicts
git push -f
```

**Comment by Rucknar** [comment]
Thanks @vincent99 Will just re-create to be safe.

**Pull request closed without merging**
