### PR TITLE
[WIP][1.6] Support Alibaba Cloud Docker Hub webhook

### PR DESCRIPTION
**Pull request by loganhz**
payload of Alibaba Cloud Docker Hub's webhook is slightly different from Docker Hub.
PR for webhook-service change is [here](https://github.com/rancher/webhook-service/pull/60)
So I have added an option in UI for it [#9175](https://github.com/rancher/rancher/issues/9175)
Also fixed the issues [#7996](https://github.com/rancher/rancher/issues/7996) and [#9022](https://github.com/rancher/rancher/issues/9022)

image
image

### CODE REVIEW

**Comment by vincent99** [comment]
Need a 2.0/`master` PR too, the `1.6-dev` branch is not ever going to be merged to `master`.

And the backend to be merged first.

**Comment by loganhz** [comment]
PR for `master` https://github.com/rancher/ui/pull/1242

**Comment by yasker** [comment]
@vincent99 Can you review this one? Thanks!

**Comment by vincent99** [comment]
Looks fine, but the backend PR isn't merged.

**Comment by yasker** [comment]
@loganhz You need to use `git rebase`, not `git merge`

**Pull request closed without merging**
