### PR TITLE
Convert node name to lowercase in registration command

### PR DESCRIPTION
**Pull request by loganhz**
## Proposed changes

`host-override` can only contain lower case alphanumeric characters, `-` or `.`.

## Types of changes

What types of changes does your code introduce to Rancher?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Issues

Link any related issues, pull-requests, or commit hashes that are relavent to this pull-request.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
_Tip: `yarn lint` or `npm run lint`_
- [x] Any dependent issues or pr's have been linked
- [ ] If updating dependencies, `yarn.lock` file has been updated and committed

## Further comments

n/a

### CODE REVIEW

**Comment by westlywright** [comment]
Does this just blindly change the node name without informing the user? Also if the nodename needs to be lowercase why is this not included in the `validateHostname` check? We should provide feedback to the user that they didn't enter a valid node name rather then just changing it for them.

**Comment by loganhz** [comment]
Added a `validateHostnameOverride` method.

`a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character`

**Comment by vincent99** [comment]
`validateHostname` only validates the name, it can't change it because it just receives the scalar string.  `validationErrors()` on a model looks for the DNS types and lowercases it on the model before validating (https://github.com/rancher/ember-api-store/blob/master/addon/models/resource.js#L140-L144)

You can (and should) just lowercase it before calling the validator though in driver-rke.

The validator already has support for restricted labels ( `validateDnsLabel(val, displayKey, intl, {restricted: true}, errors);`), but not for a hostname consisting of restricted labels.  Add an option to https://github.com/rancher/ember-api-store/blob/master/addon/utils/validate.js#L122 to pass in opts (you can make max=253 one of them and drop that param, it's never changed), then use that instead of re-implementing as `validateHostnameOverride` in this component.

**Comment by loganhz** [comment]
We need to merge the PR https://github.com/rancher/ember-api-store/pull/25 first

**Pull request merged**
