### PR TITLE
Make modal in the top of screen

### PR DESCRIPTION
**Pull request by loganhz**
https://github.com/rancher/rancher/issues/10237

### CODE REVIEW

**Comment by vincent99** [comment]
This will break scrolling of a modal that is taller than the window.  (And making the modal contents scroll is no good.  Only the `<body>` should scroll.)

What is supposed to happen is the scroll position is saved, moved up to to the top to make the modal visible, and then restored on close.  You probably just need to backport https://github.com/rancher/ui/commit/0f9cc59c5e8816083049e9c5aabdace9b7f2117b

**Comment by loganhz** [comment]
Thanks @vincent99 .
Can I just copy and override the modal service from add-on?

**Comment by vincent99** [comment]
Defining a service that isn't referenced isn't going to do anything.. In 1.x it's in https://github.com/rancher/lacsso/blob/master/addon/services/modal.js and pulled in via NPM.

**Comment by loganhz** [comment]
Thanks Vince.
PR for lacsso is https://github.com/rancher/lacsso/pull/11

**Pull request merged**
