### PR TITLE
Wrap log lines

### PR DESCRIPTION
**Pull request by loganhz**
https://github.com/rancher/rancher/issues/13636

### CODE REVIEW

**Comment by vincent99** [comment]
This should be optional with a "Wrap lines" checkbox in the log screen, and remember the state as a user setting (which can default to on/wrap).  

Wrapping is very unhelpful in some situations like when you're watching wide lines that vary slightly at the end but you don't care much about that end part, e.g. web server access logs.

**Comment by loganhz** [comment]
@vincent99 Updated. Thanks for your review

**Comment by vincent99** [comment]
Setting values are automatically JSON encoded/decoded by the service... So you can use regular `true`/`false`.

Otherwise LGTM

**Comment by loganhz** [comment]
@vincent99 Updated

**Pull request merged**
