### PR TITLE
[WIP] Read Certificate SANs from list

### PR DESCRIPTION
**Pull request by superseb**
Needs backend: https://github.com/rancher/rancher/issues/14718 / https://github.com/rancher/types/pull/516

https://github.com/rancher/rancher/issues/14745

### CODE REVIEW

**Comment by loganhz** [comment]
It looks good. We need to merge backend change first.

**Comment by loganhz** [comment]
@superseb It looks like your backend change has been merged into rancher/rancher:master

I have tried to create a certificate with `Subject Alternative Name`. But after adding it into Rancher, the `subjectAlternativeNames` filed is `null` in API. Not sure if it is a backend issue or it is an issue of my self-signed certificate.

Can you have a look, please? Thanks

**Comment by superseb** [comment]
Types is merged but not yet vendored into `rancher/rancher`

**Comment by loganhz** [comment]
image

It looks like the type is already `array[string]`

**Comment by alena1108** [comment]
@loganhz @superseb all backend fixes are in master now

**Pull request merged**
