### PR TITLE
Logging issue

### PR DESCRIPTION
**Pull request by n313893254**
Proposed changes
======

1. File target will synch with the form target.
2. Fix Kafka SASL issue.
3. Add CA config for custom target.
4. Change the custom target CA path format.

5. https://github.com/rancher/rancher/issues/17829
Add `enableTls` for syslog, and refactor syslog `willSave`  function. It needs backend merged first.

Types of changes
======

- Bugfix (non-breaking change which fixes an issue)

Linked Issues
======
https://github.com/rancher/rancher/issues/17751
https://github.com/rancher/rancher/issues/17659
https://github.com/rancher/rancher/issues/17697
https://github.com/rancher/rancher/issues/17598
https://github.com/rancher/rancher/issues/17829

 

Further comments
======

### CODE REVIEW

**Comment by westlywright** [comment]
@n313893254 when the backend is merged can you remove the `waiting-end-changes` label?

**Comment by n313893254** [comment]
Sure

**Comment by n313893254** [comment]
Remove "Add system log option" commit because of waiting for backend change https://github.com/rancher/rancher/issues/17228#issuecomment-459454091

**Comment by loganhz** [comment]
@westlywright backend is in

**Pull request merged**
