### PR TITLE
Add OTC CCE label translation

### PR DESCRIPTION
**Pull request by outcatcher**
Proposed changes
======
This is PR for adding a verbose label for OpenTelekomCloud CCE driver:
https://github.com/rancher/rancher/pull/30286/

Types of changes
======
New feature

Linked Issues
======
rancher/rancher#30286

Further comments
======

This is a minimal possible change for built-in OTC CCE driver support.
UI component is managed under [opentelekomcloud/ui-cluster-driver-otc](https://github.com/opentelekomcloud/ui-cluster-driver-otc/)

### CODE REVIEW

**Review by westlywright — CHANGES_REQUESTED** [review]
You'll need to add one more translation under `kontainerDriver.displayName.otccceEngineConfig: Open Telekom Cloud CCE` to ensure you get the same display name on the Global drivers page.

**Comment by outcatcher** [comment]
@westlywright What name of the driver should be in this mapping? Same as a driver name in `rancher/rancher`? 
I can see in `en-us.yaml` the following:
```yaml
kontainerDriver:
  displayName:
    aliyunkubernetescontainerservice: Alibaba ACK
    ...
    oraclecontainerengine: Oracle OKE
```

**Comment by dramich** [comment]
https://github.com/rancher/rancher/issues/30297

**Comment by westlywright** [comment]
> @westlywright What name of the driver should be in this mapping? Same as a driver name in `rancher/rancher`?
> I can see in `en-us.yaml` the following:
> 
> ```yaml
> kontainerDriver:
>   displayName:
>     aliyunkubernetescontainerservice: Alibaba ACK
>     ...
>     oraclecontainerengine: Oracle OKE
> ```

The key for the driver should match the kontainer driver name exactly

https://github.com/rancher/ui/blob/master/app/models/kontainerdriver.js#L35

**Comment by outcatcher** [comment]
Set translation for driver name set in https://github.com/rancher/rancher/pull/30286 (`opentelekomcloudcontainerengine`)

**Review by westlywright — APPROVED** [review]

**Pull request merged**
