### PR TITLE
Expose new ui setting for issues email link

### PR DESCRIPTION
**Pull request by codyrancher**
Proposed changes
======
expose a new setting for the UI that allows the user to input an email and use mailto links in the footer for `file an issue` instead of sending the user to rancher Github issues.

Types of changes
======

Linked Issues
======
rancher/rancher#27047
 

Further comments
======
backend pr https://github.com/rancher/rancher/pull/27136

### CODE REVIEW

**Comment by codyrancher** [comment]
@vincent99 both this pr and the original wes published didn't allow you to edit the setting. It looks like it requires a backend change to support this, is that correct?

**Comment by vincent99** [comment]
All settings are editable in the API by default, but you can add it to https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/constants.js#L554 if you want it to be editable from the admin settings UI...

**Comment by vincent99** [comment]
64k of parser lib to decide if `mailto:` should be prepended seems...excessive?  I'd just use `.contains('@')`, or better yet just not do anything and use the value as given; if you want an email instead of a link, you set the value to `mailto:foo@bar.com`.

That also allows the various query params (`subject`, `cc`, `bcc`, `body`) that mailto links support to be used if they want.

The server PRs still need the option renamed to match here and should be merged first.

**Comment by codyrancher** [comment]
> 64k of parser lib to decide if `mailto:` should be prepended seems...excessive? I'd just use `.contains('@')`, or better yet just not do anything and use the value as given; if you want an email instead of a link, you set the value to `mailto:foo@bar.com`.
> 
> That also allows the various query params (`subject`, `cc`, `bcc`, `body`) that mailto links support to be used if they want.
> 
> The server PRs still need the option renamed to match here and should be merged first.

Just doing the raw url is fine with me so I'll switch to that. It's how I originally had it but I didn't feel it stuck with the intent of the original PR. Valid urls can contain '@' https://stackoverflow.com/questions/19509028/can-i-use-an-at-symbol-inside-urls.

**Comment by vincent99** [comment]
Yes, "Just tell me the href you want" is simpler and better.

I'm aware, you could also put in `http://user:pass@host/`.  But both are exceedingly unlikely uses of a rarely used setting, vs the overhead of a pedantic library to check it in every installation.

And it would still have different edge cases anyway, e.g. `/foo/@bar` is a "valid" email, but also a root-relative path that would also work as a regular href.  Email validation is a bottomless pit.

**Pull request merged**
