### PR TITLE
Add colon to templates that utilize generic.restarts and generic.podRestarts

### PR DESCRIPTION
**Pull request by davidnuzik**
Proposed changes
======

Add a colon to the end of "Pod Restarts" and "Restarts" (generic.podRestarts, generic.restarts) for improved formatting and readability. One template has this but they all should where needed.

Types of changes
======

Bugfix, non-breaking

Linked Issues
======
 
https://github.com/rancher/rancher/issues/17891

Further comments
======

Adds a colon in these areas:
Screen Shot 2019-04-30 at 2 34 34 PM
Screen Shot 2019-04-30 at 2 33 52 PM

Pod Restarts > Pod Restarts:
Restarts > Restarts:

### CODE REVIEW

**Comment by davidnuzik** [comment]
@loganhz I think this might actually break the container detail page. For some reason only there we manually add a colon it to the template. I should probably fix this just need to figure out where template is.

image

**Comment by davidnuzik** [comment]
I think this is it https://github.com/rancher/ui/blob/master/app/container/template.hbs#L57

**Comment by davidnuzik** [comment]
I got guidance from Wes @loganhz FYI I will modify the templates the use generic.restarts and generic.podRestarts so they now contain a colon.

**Comment by loganhz** [comment]
Thanks! LGTM

**Pull request merged**
