### PR TITLE
Bugfix link in local cluster

### PR DESCRIPTION
**Pull request by wirwolf**
related https://github.com/rancher/rancher/issues/30990

### CODE REVIEW

**Comment by wirwolf** [comment]
ping @westlywright

**Comment by westlywright** [comment]
@wirwolf Thanks for the PR! We're currently in the middle of a release and resources are a little low, so I apologize for the slow response. Initially I dont see anything wrong with the PR. I want to run it and read some of the surrounding code so I may have a more clear picture of the scope of the change before merging, but I suspect by the looks of it that the change is low impact.

**Comment by wirwolf** [comment]
Hello @westlywright. Any updates?

**Comment by westlywright** [comment]
@wirwolf Sorry, wanted to get some confirmation from QA. We're good. I'm merging in to master and I'll backport the change to our 2.5-fixes branch so it makes it into the next 2.5.x release. Thanks.

**Pull request merged**
