### PR TITLE
Fix incorrect status bar issue in node dashboard

### PR DESCRIPTION
**Pull request by loganhz**
Proposed changes
======
Fix incorrect status bar issue in node dashboard

Types of changes
======
- Bugfix (non-breaking change which fixes an issue)

Linked Issues
======
https://github.com/rancher/rancher/issues/17767
 

Further comments
======

### CODE REVIEW

**Comment by bongaquino** [comment]
Is this already applied to version 2.1.7?

**Comment by vincent99** [comment]
No.  https://github.com/rancher/rancher/issues/18733

**Comment by bongaquino** [comment]
so that's why, I still have it. 

Would be mine please telling me the path of that file? So that I can edit my Rancher UI.

**Comment by ainiml** [comment]
@bongaquino see https://github.com/loganhz/ui/commit/f44b8ec14f2c25567304f611c08e0f46cc3610df

**Pull request merged**
