### PR TITLE
A tenancy should be a valid compartment since it is technically the r…

### PR DESCRIPTION
**Pull request by jlamillan**
Proposed changes
======
This change updates the (JavaScript) validation logic to allow the tenancy to be used as a valid compartment since it is technically the 'root compartment'.

The driver nor the OKE platform have issues provisioning a cluster and VCN to the root compartment / tenancy. Therefore, we should loosen up the overly restrictive validation. 

Types of changes
======

- Bugfix (non-breaking change which fixes an issue)

Linked Issues
======

[Here](https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/13)

Further comments
======

Backwards compatible change.

### CODE REVIEW

**Comment by westlywright** [comment]
@jlamillan Should this also go back into our 2.4.x branch? Master is the next release after 2.4 and as a result this change wouldn't show up in the next 2.4 maintenance release.

**Comment by jlamillan** [comment]
> @jlamillan Should this also go back into our 2.4.x branch? Master is the next release after 2.4 and as a result this change wouldn't show up in the next 2.4 maintenance release.

A backport into 2.4.x would be good.

**Comment by Pelrauns** [comment]
Hi,
   I'm still facing this problem in v2.4.8.

Regards,

**Comment by jlamillan** [comment]
Hi @Pelrauns. The issue you are describing originally affected _both_ the OKE cluster driver and the OCI node driver. 

The  [fix](https://github.com/rancher/ui/pull/4038) I put in was _only_ on the OKE cluster side, which is why you are still seeing it in the OCI node driver.

I'll submit a fix and ask that it also be back-ported. Sorry for the confusion.

**Comment by jlamillan** [comment]
@Pelrauns, the fix was merged. 

Update your `ui-index` to pick it up i.e.

Global => Settings => ui-index = `https://releases.rancher.com/ui/latest-2.4/index.html`

**Comment by Pelrauns** [comment]
@jlmillan Thanks! Will do!

**Comment by jlamillan** [comment]
Also, be sure to use the latest version of the OCI Driver i.e. https://github.com/rancher-plugins/rancher-machine-driver-oci/releases/download/v1.0.1/docker-machine-driver-oci-linux

**Pull request merged**
