### PR TITLE
fix bug of https://github.com/rancher/rancher/issues/9575

### PR DESCRIPTION
**Pull request by orangedeng**
fixed bug of https://github.com/rancher/rancher/issues/9575

### CODE REVIEW

**Comment by yasker** [comment]
Hi @vincent99 

Can you give a quick look? We have a customer asking for this

**Comment by vincent99** [comment]
@yasker A PR to 2.0 (`master`) isn't going to help a customer..

**Comment by yasker** [comment]
Oops… @orangedeng can you rebase this to 1.6-dev?

**Comment by yasker** [comment]
@orangedeng In fact you will need a PR to 2.0 and a PR to 1.6-dev.

**Comment by orangedeng** [comment]
@yasker New Pr from 1.6-dev is https://github.com/rancher/ui/pull/1319

**Pull request merged**
